### ISSUE TITLE
エラー 指定されたURLは、アプリケーションの設定で許可されていません。

### ISSUE THREAD

**Issue by ghost** [daisuzu/facebook.vim#2]
Windows 10 Pro 10586 amd64 + Python 3.5.1 + Vim 7.4 (2013 Aug 10) 環境で，エラーにより Facebook 認証を完了できません。下記問題について回避策など有りましたら教えていただけますでしょうか。

`:FacebookHome` または `:FacebookAuthenticate` を実行すると，「エラー」という題で下記メッセージが表示されているウェブページに飛ばされてしまい，認証を完了することができません。

> 指定されたURLは、アプリケーションの設定で許可されていません。: 指定されたURLの中にアプリの設定で認められないものが含まれています。ウェブサイトまたはキャンバスのURLと一致しているか、ドメインがアプリのドメインのサブドメインである必要があります。

`python fb_auth.py %USERPROFILE%\.fb_access_token` を直接実行しても同じ問題が発生します。`fbconsole` にて `authenticate()` を実行した場合には，公開プロフィールの権限のみを要求する認証画面が正しく表示されることを確認しています。

**Comment by daisuzu** [comment]
Facebook側で色々と変わっていたのに全くメンテナンスできていませんでした...

一時的な対応としては外部パッケージに手を入れることになってしまいますが、

1. fb_auth.pyがimportしているfbconsoleのauthenticate()の`local.fbconsole.com`を`localhost`に変更したら少し先に進みました

  * before
    ```py
        if needs_auth:
            webbrowser.open(oauth_url(
                    APP_ID,
                    'http://local.fbconsole.com:%s/' % SERVER_PORT, AUTH_SCOPE
                    ))
    ```

  * after
    ```py
        if needs_auth:
            webbrowser.open(oauth_url(
                    APP_ID,
                    'http://localhost:%s/' % SERVER_PORT, AUTH_SCOPE
                    ))
    ```

2. ただfb_auth.pyで設定している権限そのままではエラーになってしまうので適宜コメントアウトすることで.fb_access_tokenが生成できるようになりました

プラグイン側でどう修正するかはちょっと考えてみます。

**Comment by miriyagi** [comment]
ありがとうございます。今確認したら Last Commit が 2 years ago でしたね。変に掘り返してしまったようでしたらすみません……

[fbsamples/fbconsole の README.md] (https://github.com/fbsamples/fbconsole) を見ると
> For the authentication flow to work, you must configure your Facebook app correctly by setting the "Site URL" option to `http://local.fbconsole.com:8080`.

と有るので，恐らく facebook.vim のアプリケーション登録で指定している URL が有るのであれば，それを fbconsole のものに変更すれば取り敢えずは動くような気がします。ただ，Facebook アプリケーションを開発した経験は無いので，見当違いのことを言っているかも知れません。

**Comment by daisuzu** [comment]
ありがとうございます。

`Site URL`は昨日やったと思ったのですが、別のパラメータ設定が間違っていて反映されていないだけでした。
なので設定を反映させて権限を da12687446204d735321e28e49cd5504ef152453 で修正したので試してみてください。

(最近はコンソールがメインなので)ほとんど使わなくなってしまいましたが不具合などには対応していくつもりなので何かあればIssuesなどにあげていただければと思います。

**Comment by miriyagi** [comment]
ありがとうございます。アプリ設定は流石に PullRequest ではどうにもできないので助かります。無事認証ページまで飛べるようになりました。

ただ，`:FacebookHome` は `(#200) Requires extended permission: read_stream` で相変わらず利用できない状況です。`fb_auth.py` に `read_stream` を追加，[Facebook のアプリ設定] (https://www.facebook.com/settings?tab=applications) で FB4Vim の認証を取り消し，`.fb_access_token` を削除した上で再度試してみましたが，やはり同じエラーが出ます。そもそも FB4Vim の認証画面ではパブリックプロフィールとメールアドレスへのアクセス程度しか付与できない（ストリームの読み込みや書き込みの権限を与えることができない）ので，登録アプリの権限設定が別途必要なのかもしれません。再度確認いただけますでしょうか。

**Comment by daisuzu** [comment]
ドキュメントにも書いてありましたが、`:FacebookHome `には`read_stream`が必要でした。
私の環境ではFacebook上からFB4Vimを削除して 3a4fe3541973da0ed0e1a5f40c6aa3564c34098a の権限で再登録したら使えるようになりました。

**Comment by miriyagi** [comment]
対応ありがとうございます。ただ，残念ながら私の環境では前述の状況が引き続き発生している状況です。

どうやら [Facebook API v2] (https://developers.facebook.com/docs/apps/api-v1-deprecation) の導入に伴い，追加権限を利用するアプリケーションでは [Facebook Login Review] (https://developers.facebook.com/docs/facebook-login/review/what-is-login-review) が必要となったようです。既にレビューを受けられているのでなければ，これにより開発者以外がホームを読めなくなってしまったのかもしれません。

更に悪いことに，[`read_stream` は v2.4 で廃止] (https://developers.facebook.com/docs/apps/changelog#v2_4_deprecations)されていて，しかも[代替案が無い] (http://stackoverflow.com/questions/28634392/alternative-to-facebook-read-stream)ようです。それを使うアプリケーションのレビューは通らないでしょうし，たとえ通ったとしても Facebook のタイムラインを Vim から読むのは[遅かれ早かれ] (https://developers.facebook.com/docs/apps/changelog)できなくなるように思います。

ですので，この Issue については Fixed で解決とし，ホームが読めないという問題は By Design として諦めることになるのではないかと考えています。

**Comment by daisuzu** [comment]
色々と調べていただいてありがとうございます。
iOSやAndroidの3rd−partyアプリから`:FacebookHome`相当の機能が無くなっていたのは知っていましたがそういうことだったんですね。。。
それではdeprecatedな権限は[削除](https://github.com/daisuzu/facebook.vim/commit/e1a91be0cf98cb64e86cb2a28cf0f268e30d565a#diff-1bc7a1c82773afc67019d6e38183bf52)してこちらはcloseにしておきます。
